### ISSUE TITLE
Add support for imported views

### ISSUE THREAD

**Issue by asg017** [asg017/unofficial-observablehq-compiler#1]
I haven't tested this, but I'm pretty sure this won't work:

## Notebook 1
```
viewof a = DOM.input()

md`Typed value: "${a}"`
```

## Notebook 2

```javascript

import {viewof a} from 'notebook1'

viewof a

md`This notebook's value: ${a}`
```

Supporting this `viewof` import would be awesome!

**Comment by bryangingechen** [comment]
I can tackle this and #2 if you're not already working on this.

**Comment by asg017** [comment]
@bryangingechen sure, that would be awesome!

The parser [already tells us](https://github.com/observablehq/parser#specifier_view) if the imported cell is a view or not, so this issue should be a simple if statement on that boolean, then importing the `viewof x` instead of `x`. Implemenring the `mutable` keyword may be a little more fun...
