### ISSUE TITLE
Running notebooks locally

### ISSUE THREAD

**Issue by miketahani** [asg017/unofficial-observablehq-compiler#17]
Not sure if this is the right place to ask this – please let me know if it isn't.

How can I compile and run a notebook locally? E.g., the example at the top of the README – how do I point the compiler at local versions of the dependencies (like `@jashkenas/inputs`, `md` from the stdlib)?

Running the example [here](https://github.com/asg017/unofficial-observablehq-compiler/blob/master/test/test.html) gives me `Uncaught TypeError: e is not a function`.

Thanks!

**Comment by bryangingechen** [comment]
Here are my steps to get the test working locally:

1. clone the repo:
    ```bash
    git clone git@github.com:asg017/unofficial-observablehq-compiler.git
    cd unofficial-observablehq-compiler/
    ```

2. build the compiler:
    ```bash
    npm i
    npm run build
    ```

3. start a local webserver and view the test html files:
    ```bash
    npm run test-html
    ```
    navigate to e.g. http://127.0.0.1:8080/test/test.html in my browser.

Does that help?

**Comment by miketahani** [comment]
I followed those instructions exactly, but unfortunately still get the same error.

**Comment by bryangingechen** [comment]
That doesn't look like the `test/test.html` file. The `window.MODULE` line is [line 138](https://github.com/asg017/unofficial-observablehq-compiler/blob/master/test/test.html#L138) there. Do you mind sharing the full HTML file you're trying to open?

**Comment by miketahani** [comment]
The line in question is from [here](https://github.com/asg017/unofficial-observablehq-compiler/blob/master/index.html#L52), which is what gets served at http://127.0.0.1:8080 after completing all the steps in your previous comment (after starting the server with `npm run test-html`).

**Comment by miketahani** [comment]
My bad! I was hitting http://127.0.0.1:8080. I hit the full URL and it works. Thanks!

**Comment by miketahani** [comment]
So I suppose my original question should be rephrased: it looks like various outbound network calls are being made for pulling in imports – is the `resolve` argument for the compiler meant to allow redirecting of these calls, or am I totally misunderstanding what's happening here?

**Comment by bryangingechen** [comment]
Glad you got it working! Regarding `resolve`, yes that's right. The default resolver should work out-of-the-box for importing notebooks hosted on observablehq.com, and by passing a different function you can import notebook modules from anywhere you like.

**Comment by miketahani** [comment]
Got it. Thank you so much for your help, and thanks for this cool project!
