### ISSUE TITLE
Interpreting existing variable will throw a RuntimeError

### ISSUE THREAD

**Issue by Srabutdotcom** [asg017/unofficial-observablehq-compiler#31]
Hi @asg017 ,

i have tried the Interpreter by interpreting existing variable name but that would throw RuntimeError. Please take a look on the following code that i have added into interpreter-test.js line 39...

~~~javascript
await interpret.cell("b = 4", main, observer);
t.equals(await main.value("b"), 4, "b are updated from 2 to 4"); 
~~~
I think Interpreter should have ability to prevent variable duplication in observablehq runtime.
I know you have done this outside runtime. Based on my investigation, we can check existing runtime variable using runtime_scope.

**Comment by asg017** [comment]
Just answered your question in [this comment](https://github.com/asg017/unofficial-observablehq-compiler/pull/29#issuecomment-823717388), which I'll copy here:


> @Srabutdotcom if your runtime module already has a cell named `b`, then running `interpret.cell("b = 4")` will fail with a `b = RuntimeError: b is defined more than once` error. You'll either have to redefine `b` on the runtime module specifically with [`module.redefine`](https://github.com/observablehq/runtime#module_redefine), or you can capture the returned variables from the previous `interpret.cell("b = 1")` call and run [`variable.delete`](https://github.com/observablehq/runtime#variable_delete) on that. 

> See [this notebook](https://observablehq.com/d/e2b8aa5bb90ae92d) for details and code.

But to also mention here: The interpreter is not meant to solve things like defining the same cell multiple times. It's just meant to run whatever code is given on the given runtime, any error handling/variable duplication will have to be handled by whoever uses this library, or end-users  when writing their own notebooks

**Comment by Srabutdotcom** [comment]
Okay thanks for the clearence @asg017. Thus we as the end user need to develop variable duplication prevention prior interprete it.
