### ISSUE TITLE
Implement function to compile notebook JSON to ES module?

### ISSUE THREAD

**Issue by bryangingechen** [asg017/unofficial-observablehq-compiler#5]
I'm thinking of adapting the code I wrote in [this notebook](https://observablehq.com/@bryangingechen/from-raw-notebook-source-to-observable-runtime-v1-modules) to the V3 runtime format using your compiler.

Would you welcome a PR that adds a function which takes as input a notebook JSON object (maybe also a JSON string) and outputs the define function? Something to worry about here is the fact that the notebook JSON format is not in any way officially supported so it could very well change without warning. However, something like this might still be useful for the folks who have been backing up their notebooks locally [per this thread](https://talk.observablehq.com/t/backup-method/1628).

As I recall, I used the parser's `parseCell` function to implement the V1 version of this, so I might end up writing some kind of `compile.cell` function as discussed in #3.

**Comment by asg017** [comment]
Sure, this makes sense! Maybe we can have a `compile.notebook` that takes in the notebook object and compiles it into a `define` function. I'd rather the object be the input instead of a JSON string (so it's not confused with `compile.module`).

**Comment by bryangingechen** [comment]
I thought a bit more about this and there are actually two parts to this:
- The first part is just consuming a notebook object and passing it to `createModuleDefinition`. This should be straightforward to implement as soon as the other PRs are merged; the only question is picking a convenient / reusable API for `compile.cell`; I'll experiment and see.
- The second part is what I hinted at in the issue title (and the focus of the notebook I linked above). It would be nice to have a function which outputs an ES module file that exports a `define` function (like the `api.observablehq.com/-/-.js?v=3` files). I don't yet see an easy way to do this without repeating much of `createModuleDefintion` though. I'll think some more about this.

**Comment by nicola** [comment]
any way (or hint) to make this work?
this seems to me like a blocker if we want to be able to "import" local notebooks defined in this way

**Comment by bryangingechen** [comment]
I was hoping to get back to this within a few weeks or so, but if you'd like to work on it yourself, the basic idea is just to imitate the output of the files that are generated by the `https://api.observablehq.com/@:user/:notebook.js?v=3` endpoint. I couldn't tell you the exact format from memory, but roughly speaking those files begin with `import` statements for all the referenced imports, then a `define` function which creates a main module and then populates it with `variable` objects for the code cells and `module` objects for the imports. 

For the `variable` objects, we need to use the parser output to wrap the source code of each non-import cell and turn it into the source code for a variable definition (string to string). I think we may be able to reuse some of the logic in `createRegularCellDefintion` that appears before we pass things to the `Function` constructor.

Similarly, the parser output for import cells is used to create the `module` objects and the import statements at the top of the file. This will just take some fiddling.

Anyways, let me know if you start working on this. I'd be happy to give more suggestions / tips.

**Comment by bryangingechen** [comment]
I've started work on this. Hoping to PR something by the end of the week. 🤞

**Comment by bryangingechen** [comment]
This is now live as of v0.5.0. Woohoo!

**Comment by nicola** [comment]
that is awesome, thank you!
